###2019-05-07
   FE: wangkai37
   NOTE: 修复动态改变数据时，底部边线位置不更新的问题

###2019-2-19
   FE: donghualei
   NOTE: 增加data-module属性，支持在list中增加dataModule属性，组件给绑定到dom节点上

###2018-12-21
   FE: yaochang
   NOTE: 调整 PC 下的高度和字号

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-29
   FE: wangkai37
   NOTE: 增加滚动样式时对 TAB 日志类的判断

###2018-11-06
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-10-25
   FE: zhangjingyuan02
   NOTE: 解决点击响应两次click事件

###2018-09-27
   FE: wangkai37
   NOTE: 解决滚动穿透问题

###2018-09-25
   FE: wangkai37
   PM:
   NOTE: Navs 支持滚动时也跳转
   三级单:

###2018-07-17
   FE: liyuhang01
   PM:
   NOTE: 下拉区域支持自定义
   三级单:

###2018-06-22
   FE: diaojiajia
   PM:
   NOTE: NA2.0添加tab展开动画接入动效库
   三级单:

### 2018-06-13
    FE: wangkai37
    NOTE: 增加兼容处理报警

###2018-05-31
   FE: diaojiajia
   PM:
   NOTE: NA2.0添加tab展开动画
   三级单:

### 2018-05-29
    FE: songshaokang
    PM:
    NOTE: 滑动无弹层添加自定义背景色
    三级单:

### 2018-05-21
    FE: zhangjingyuan02
    PM:
    NOTE:
        1. 去掉navs点击态效果，去掉文字渐变效果
        2. 修改navs点击跳转(disableEvent为true)时的navs效果更换
        3. 去掉navs切换下划线拉伸动画
    三级单:

###2017-12-1
   FE: songshaokang
   PM:
   NOTE: 添加 tab bar 切换动画，添加点击态，添加背景文字颜色配置
   三级单:
