###2019-06-26
   FE: wangkai37
   NOTE: 增加 disableEvent 属性；增加项点击态判断

###2019-06-21
   FE: wangkai37
   NOTE: 增加横滑可点击跳转功能

###2019-04-28
   FE: wangkai37
   NOTE: 增加点击跳转功能

###2019-04-09
   FE: wangkai37
   NOTE: 修改大小

###2019-02-21
   FE:wangkai37
   NOTE:增加点击展开收起按钮的事件，增加事件参数

###2019-02-11
   FE:wangkai37
   NOTE:增加支持自定义颜色的功能

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-06
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

###2018-09-27
   FE: wangkai37
   NOTE: 解决滚动穿透问题

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-08-27
   FE: wangkai37
   NOTE: 修改格式问题；增加子组件

###2018-07-17
   FE: liyuhang01
   PM:
   NOTE: 下拉区域支持自定义
   三级单:

### 2018-06-28
   FE: zhangwentao
   NOTE: 非横滑下拉场景增加屏蔽触发整卡点击态功能

### 2018-06-22
    FE: diaojiajia
    PM:
    NOTE:
        1. 增加tag展开和收起动画效果 接入动效库
    三级单:

### 2018-05-21
    FE: zhangjingyuan02
    PM:
    NOTE:
        1. 添加tagsWrapper组件，支持tags下内容切换0.24s动画和0.08s渐显效果
    三级单:

### 2018-05-30
    FE: diaojiajia
    PM:
    NOTE:
        1. 增加tag展开和收起动画效果
    三级单: