###2019-04-02
   FE: wangkai37
   NOTE: 去除指示器长按选中的多余功能；新增样式配置

###2018-10-22
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-10-21
   FE: wangkai37
   NOTE: 增加定高功能

###2018-10-18
   FE: meiyulong
   NOTE: 支持不同尺寸的图片垂直居中显示；增加图片同步渲染开关

###2018-10-22
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-09-25
   FE: wangkai37
   NOTE: 新增 CarouselFrame（轮播框架）、Indicator（指示器） 组件

###2018-09-19
   FE: wangkai37
   NOTE: 轮播图增加是否显示指示器、是否循环的变量

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-08-21
   FE: wangkai37
   NOTE: 轮播组件二期

###2018-08-19
   FE: wangkai37
   NOTE: 增加图片比例不一致时容错处理；修改为 css module

###2018-07-02
   FE: liyuhang01
   NOTE: 修复文档问题

###2018-06-19
   FE: wangkai37
   NOTE: 首屏性能优化

###2018-06-15
   FE: wangkai37
   NOTE: 使用img替换背景图片background-size cover，修复在小屏手机上图片显示不全的问题

###2018-06-13
   FE: wangkai37
   NOTE: 轮播图组件

###2018-06-07
   FE: wangkai37
   NOTE: 轮播图组件