###2019-06-20
   FE: zhangwentao
   NOTE: JS 点击态未生效时增加 CSS 点击态降级

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-08
   FE: wangkai37
   NOTE: 修复 slink 间距和高度；删除多余文档

###2018-11-07
   FE: zhangwentao
   NOTE: 点击态改成background实现方式，修复位置变化时点击态错位

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，去掉原组件内 js 实现

###2018-10-28
   FE:liyuhang01
   NOTE:组件无障碍升级

###2018-08-14
   FE: liyuhang01
   NOTE: 新增短链尾部文字

###2018-06-28
   FE: zhangwentao
   NOTE: 支持 NA2.0 点击态