###2019-02-15
   FE: liyuhang01
   NOTE: QQ浏览器分享所需链接改为相对协议

###2018-12-06
   FE: liyuhang01
   NOTE: 增加圆角

###2018-12-11
   FE: liyuhang01
   NOTE: 支持手百 lite 端能力

###2018-10-29
   FE: wangkai37
   NOTE: 动态引入模块；增加 PC 兼容

###2018-11-22
   FE: liyuhang01
   NOTE: 删掉多余的 alert

###2018-10-25
   FE: liyuhang01
   NOTE: 更改图片引入方式

###2018-09-21
   FE: liyuhang01
   NOTE: 修复 fusion 无法调起问题

###2018-09-07
   FE: liyuhang01
   NOTE: 迁移 fusion

###2018-08-15
   FE: wangkai37
   NOTE: 修复整卡可点事件透传问题
