###2019-3-6
   FE: donghualei
   NOTE: 支持左图右文的图片区域的data-module

###2018-12-21
   FE: yaochang
   NOTE: 调整 PC 下的左图右文栅格数

###2018-09-21
   FE: liyuhang01
   NOTE: 修复 aira-hidden 不加 true 值不生效问题

###2018-09-10
   FE: liyuhang01
   NOTE: 增加组件无障碍支持

###2018-06-28
   FE: wangkai37
   NOTE: 增加error事件；增加直接采用背景图片的方式

###2018-05-24
   FE: zhangwentao
   NOTE: 图片点击态增加开关，通过 `img-touchable` 配置，保持默认打开

###2018-01-08
   FE: wangkai37
   PM:
   NOTE: 图片增加点击事件
   三级单:

###2017-12-1
   FE: yaochang
   PM:
   NOTE: 图片添加点击态
   三级单:


