###2019-05-23
   FE: wangkai37
   NOTE: 给L1S2策略增加是否有标签的判断

###2019-05-07
   FE: wangkai37
   NOTE: 增加标题粗细参数 fontWeight

###2019-04-11
   FE: wangkai37
   NOTE: 增加标题截断策略

###2018-12-21
   FE: yaochang
   NOTE: PC 下修改默认栅格数

###2018-12-17
   FE: wangkai37
   NOTE: 增加右侧文字

###2018-11-28
   FE: wangkai37
   NOTE: 增加 data-module

###2018-11-06
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-10-08
   FE: wangkai37
   NOTE: 增加 PC 兼容

###2018-09-28
   FE: wangkai37
   NOTE: 增加 color props

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

### 2018-07-31
    FE: wangkai37
    NOTE: 修改一级标题截断方式

### 2018-06-28
    FE: wangkai37
    NOTE: 修改二级标题截断方式
