###2019-04-15
   FE: wangkai37
   NOTE: 增加强制 better-scroll 的配置；增加通过 js 滑动到指定位置的方法

###2019-04-08
   FE: wangkai37
   NOTE: 增加 iOS9 的兼容

###2019-02-26
   FE: wangkai37
   NOTE: ScrollAuto 低版本兼容结构修改

###2019-01-14
   FE: liyuhang01
   NOTE: 新增 more slot

###2019-01-08
   FE: wangkai37
   NOTE: 修复 iOS 弹性滚动时多次触发 scrollend 的问题

###2018-11-23
   FE: wangkai37
   NOTE: 增加 ScrollAuto 降级

###2018-11-06
   FE: wangkai37
   NOTE: 增加 ScrollAuto 自适应；修复 snap 右侧栅格对不齐的问题

###2018-11-01
   FE: wangkai37
   NOTE: 修复 vnode.componentOptions 不存在时的兼容性问题

###2018-10-27
   FE: wangkai37
   NOTE: 增加 snapStepX 参数，控制 snap 时滑动的距离

###2018-10-17
   FE: wangkai37
   NOTE: 增加弹性参数，暴露滚动事件

###2018-08-07
   FE: wangkai37
   NOTE: 增加 ScrollInner 组件

###2018-07-06
   FE: wangkai37
   NOTE: 修复更换 better-scroll 后 snap 不正确的问题

### 2018-07-06
    FE: zhangwentao
    NOTE: scroller 支持 flex 布局，默认关

###2018-06-04
   FE: yaochang
   NOTE: 增加 schema

### 2018-1-15
    FE: zhangbing10
    PM:
    NOTE: 修复定位滚动时，最后一个元素展现不全的问题
    三级单:

### 2017-11-24
    FE: yaochang
    PM:
    NOTE: 修复 scroll-item 不等宽时，padding-right 不一致的 bug
    三级单:

###2017-11-10
   FE: yaochang
   PM:
   NOTE: 支持栅格套栅格
   三级单:

###2017-07-07
   FE:wukaifang
   PM:lixiao12
   NOTE:atom的c-scroll组件
   三级单:

###2017-10-24
   FE:huxiaohui02
   PM:lixiao12
   NOTE:增加滑动后定位到元素功能
   三级单:
