###2019-06-20
   FE: zhangwentao
   NOTE: JS 点击态未生效时增加 CSS 点击态降级

###2019-04-28
   FE: wangkai37
   NOTE: 增加对业务图标的支持

###2019-03-14
   FE: wangkai37
   NOTE: 修复修改主颜色图标不变色的问题

###2019-02-11
   FE: wangkai37
   NOTE: 优化改变颜色的逻辑，增加 primaryColor 也能改变普通按钮颜色的功能

###2018-12-03
   FE: wangkai37
   NOTE: 图片圆角

###2018-11-07
   FE: zhangwentao
   NOTE: 点击态改成background实现方式，修复位置变化时点击态错位

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，去掉原组件内 js 实现

###2018-09-17
   FE: wangkai37
   NOTE: 增加按钮栏组件；修复按钮图标颜色

###2018-09-10
   FE: liyuhang01
   NOTE: 增加组件无障碍支持

###2018-06-28
   FE: zhangwentao
   NOTE: 支持 NA2.0 点击态
