###2019-04-15
   FE: wangkai37
   NOTE: 增加与展开收起组件一起使用的示例

###2019-03-27
   FE: wangkai37
   NOTE: 修复 FilterEnhanced init 方法视图不更新的问题

###2018-11-21
   FE: wangkai37
   NOTE: 修复 Tab 嵌套 Content 时首屏选中项的索引不是第一个元素导致的问题

###2018-11-20
   FE: wangkai37
   NOTE: 修复只有一个 slot 且竖直切换动效打开时，切换无效的问题；修复 UIWebview 时，首屏滑动不流畅的问题

###2018-11-13
   FE: wangkai37
   NOTE: 修复筛选选项错位问题

###2018-11-08
   FE: wangkai37
   NOTE: 修复首屏选中项的索引不是第一个元素导致的问题

###2018-09-10
   FE: wangkai37
   NOTE: 新增动效开关

###2018-08-20
   FE: wangkai37
   NOTE: 新增内容组件