###2019-05-05
   FE: wangkai37
   NOTE: 增加 defaultValue watch 监听的示例

###2019-04-28
   FE: wangkai37
   NOTE: 范围输入框优化错误提示显示，增加不显示错误提示的控制属性

###2019-03-19
   FE: wangkai37
   NOTE: 修复范围输入框在复合筛选栏高度没有达到最大高度时，展开收起导致高度不正确的问题

###2019-02-13
   FE:wangkai37
   NOTE:增加自定义颜色功能

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-06
   FE: liyuhang01
   NOTE: 增加错误无障碍提示

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

###2018-09-10
   FE: wangkai37
   NOTE: 增加范围输入组件

###2018-08-30
   FE: wangkai37
   NOTE: 增加控制外边距参数

###2018-08-29
   FE: wangkai37
   NOTE: 修正 z-index 问题；修正 rightText 问题

###2018-08-27
   FE: wangkai37
   NOTE: 修正高度

###2018-08-14
   FE: liyuhang01
   NOTE: 修复 iOS 光标高度问题

###2018-08-09
   FE: siwenyu
   NOTE: 添加focus

###2018-07-24
   FE: liyuhang01
   NOTE: 增加左侧固定文字 左右固定文字支持不定长

###2018-06-27
   FE: zhangwentao
   NOTE: 增加 data-touchable 屏蔽触发整卡点击态

###2018-05-18
   FE:wangkai37
   NOTE:删除 z-index 属性；

###2018-02-07
   FE:wangkai37
   NOTE:增加主颜色、是否显示关闭图标和右侧文案属性；