###2018-12-21
   FE: yaochang
   NOTE: PC 下支持设置 target，默认新打开窗口

###2018-11-14
   FE: fanyurong
   NOTE: 小程序调起统一加data-xcx标识

###2018-11-07
   FE: wangkai37
   NOTE: 增加 target 示例

###2018-10-08
   FE: fanyurong
   NOTE: 小程序调起升级

###2018-09-27
   FE: wangkai37
   NOTE: 增加 url、params props 容错

###2018-05-24
   FE: wangkai37
   NOTE: 删除 data-xse 属性；完善 rtDisable、fastUrl 属性文档

###2018-05-17
   FE: wangkai37
   NOTE: 增加额外的html标签属性：data-xse、rt-disable、origin-url

