###2019-03-29
   FE:wangkai37
   NOTE:将类名不分行写，修复分行写在未压缩代码的情况下导致不生效的问题

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-06
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

### 2018-09-30
   FE: wangkai37
   NOTE: php 强制转换行数为整型，修复服务端不渲染的问题

### 2018-07-26
   FE: wangkai37
   NOTE: 增加主动设置单选选中项索引方法

### 2018-06-28
   FE: zhangwentao
   NOTE: 增加屏蔽触发整卡点击态功能

###2018-05-14
   FE:wangkai37
   NOTE:增加自定义栅格功能；增加等分功能；增加禁用点击态时不发tc日志功能；

###2018-05-07
   FE:wangkai37
   NOTE:修复单选多选时next-page下点击后状态改变不生效的问题

###2018-03-09
   FE:wangkai37
   NOTE:补充点击日志及滑动结束日志

###2018-03-08
   FE:wangkai37
   NOTE:增加滑动

###2018-02-08
   FE:wangkai37
   NOTE:修复自适应一行最多只能显示3个的问题；优化 list[].selected 属性，由必填修改为选填

###2018-02-06
   FE:wangkai37
   NOTE:修复rowNum行数只在mounted中更新的问题；

###2018-01-24
   FE:wangkai37
   NOTE:增加TagGroup多选自适应；和禁用交互状态

###2018-01-22
   FE:wangkai37
   NOTE:修复华为P10自带浏览器样式显示错误的问题