###2019-03-27
   FE: wangkai37
   NOTE: 增加 close 方法；修复 init 方法视图不更新的问题；增加 noSpread 控制 RangeInput 是否显示展开收起；

###2019-03-19
   FE: wangkai37
   NOTE: 修复范围输入框在复合筛选栏高度没有达到最大高度时，展开收起导致高度不正确的问题

###2019-03-07
   FE: wangkai37
   NOTE: 增加主动设置 selectedIndex 的方法

###2019-02-21
   FE: wangkai37
   NOTE: 修复复合筛选栏高度没有达到最大高度时，展开收起导致高度不正确的问题

###2019-02-14
   FE: wangkai37
   NOTE: 增加复合类型隐藏按钮栏的选项

###2019-02-13
   FE: wangkai37
   NOTE: 筛选组件增加新的样式功能支持；多重筛选增加自定义颜色支持

###2018-11-21
   FE: wangkai37
   NOTE: 增加调用 init 方法的示例

###2018-11-20
   FE: wangkai37
   NOTE: 增加主颜色参数

###2018-11-19
   FE: wangkai37
   NOTE: 修复排序类型时 change 事件返回值不正确的问题

###2018-10-23
   FE: wangkai37
   NOTE: 修复 Filter 没有透传 z-index 属性的问题

###2018-09-10
   FE: wangkai37
   NOTE: 筛选组件拆分

###2018-08-29
   FE: wangkai37
   NOTE: 修复 Input 改动导致的问题

###2018-06-19
   FE: wangkai37
   NOTE: 增加 checkboxclick 多选项点击事件

###2018-06-04
   FE: wangkai37
   NOTE: 增加 schema

###2018-06-04
   FE: wangkai37
   NOTE: 修复不加动效时 Android 手百复合筛选不显示底部按钮栏的问题

###2018-05-28
   FE: wangkai37
   NOTE: 动效升级；修复默认值传空字符串''认为是空的问题；增加复合布局去掉标签和去掉展开收起功能的问题；增加自定义布局的功能；

###2018-04-02
   FE: wangkai37
   NOTE: FilterEnhanced 升级；增加动效；底部距离修改；浮层最大高度限制；

###2018-04-02
   FE: wangkai37
   NOTE: FilterEnhanced 修改多级筛选最大高度为 7.5 行；

###2018-03-14
   FE: wangkai37
   NOTE: FilterEnhanced 筛选组件问题修复；

###2018-02-09
   FE: wangkai37
   NOTE: FilterEnhanced 筛选组件；