###2019-06-12
   FE: liyuhang01
   NOTE: 提出内联样式

###2019-04-13
   FE: wangkai37
   NOTE: 新增自定义圆角边距功能

###2019-03-25
   FE: wangkai37
   NOTE: 新增自定义默认图功能，替换原有默认图；ImageMask 增加 pc 的兼容

###2018-12-18
   FE: wangkai37
   NOTE: 增加左下角文字气泡

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-12-03
   FE: wangkai37
   NOTE: 图片圆角

###2018-10-30
   FE: wangkai37
   NOTE: 增加模糊渐显

###2018-10-26
   FE: wangkai37
   NOTE: 修复错误写法导致额外请求的问题

###2018-10-23
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-07-12
   FE: wangkai37
   NOTE: 1.增加修改背景颜色属性、是否显示默认图属性；2.增加高度是否自适应属性；3.补充增加直接采用背景图片的方式

###2018-06-28
   FE: wangkai37
   NOTE: 修改文档，增加事件说明；增加直接采用背景图片的方式；优化代码逻辑

### 2018-05-21
    FE: zhangjingyuan02
    PM:
    NOTE:
        1. 添加 图片渐显 效果，并添加开关，默认不使用
    三级单:

###2018-05-17
   FE: wangkai37
   NOTE: 增加胶囊遮罩大号字体文案；

