###2018-12-14
   FE: wangkai37
   NOTE: 圆角

###2018-10-23
   FE: liyuhang01
   NOTE: 支持无障碍

###2018-08-28
   FE: liyuhang01
   NOTE: 新增最小高度 是否使用动效 是否隐藏头部 是否显示 padding 四个 props

###2018-08-28
   FE: wangkai37
   NOTE: 修复 Android 闪屏的问题

###2018-07-25
   FE: wangkai37
   NOTE: 修复滚动穿透的问题

###2018-06-13
   FE: wangkai37
   NOTE: 修改 a-show 为 a-if，修复偶现的浮层不显示的问题

###2018-05-23
   FE: zhangwentao, wangkai37
   NOTE: 使用动效库升级动效

###2018-04-26
   FE: wangkai37
   NOTE: 修复 Popup 有左侧功能区时，标题过长时截断不正确的问题；修改默认最大高度传递方式

###2018-04-18
   FE: wangkai37
   NOTE: 修复 Popup 问题

###2018-04-12
   FE: haoyan
   NOTE:【Popup】支持自定义头/底部功能