###2019-06-03
   FE: wangkai37
   NOTE: 增加顶部文字的内部间距配置；增加顶部文字 slot

###2019-04-08
   FE: wangkai37
   NOTE: 增加 threshold 监听；增加右下角按钮定位参数

###2019-03-29
   FE:wangkai37
   NOTE:删除多余 height 判断

###2019-02-28
   FE:wangkai37
   NOTE:增加点击按钮次数保护，避免一些 Android 机型偶现触发两次点击事件的问题；增加 Android 手百兼容性处理

###2019-02-21
   FE:wangkai37
   NOTE:增加点击展开收起按钮的事件，增加事件参数

###2019-01-16
   FE:wangkai37
   NOTE:增加底部按钮颜色参数

###2018-12-03
   FE:wangkai37
   NOTE:修复不加动效时顶部展开收起异常的问题

###2018-11-30
   FE:wangkai37
   NOTE:iOS8 动效降级

###2018-11-23
   FE:wangkai37
   NOTE:增加右下角图标自定义颜色的功能

###2018-10-28
   FE:liyuhang01
   NOTE:组件无障碍升级

###2018-10-26
   FE: wangkai37
   NOTE: 增加参数控制点击按钮是否发送日志

###2018-10-24
   FE: wangkai37
   NOTE: 增加底部按钮边线配置

###2018-10-23
   FE: wangkai37
   NOTE: 修复在总高度小于最小高度时依然显示展开收起按钮的问题

###2018-10-18
   FE: wangkai37
   NOTE: 修复变更展开收起按钮文字时机不正确导致日志错误的问题

###2018-10-16
   FE: wangkai37
   NOTE: 增加列表类型阶段展开功能

###2018-10-12
   FE: wangkai37
   NOTE: 修复默认展开时获取不到正确参数的问题

###2018-09-10
   FE: wangkai37
   NOTE: 增加内容高度小于fold-height时不显示展开收起按钮的功能；

###2018-08-29
   FE: wangkai37
   NOTE: 增加 list 类型默认展开功能；增加上方按钮 padding、touchfeedback 参数；

###2018-08-27
   FE: wangkai37
   NOTE: 增加 rowTile 通栏参数

###2018-08-17
   FE: wangkai37
   UE: zhuxiaolei
   NOTE: 修改展开收起组件底部按钮间距

###2018-08-14
   FE: wangkai37
   UE: zhuxiaolei, yangqiu
   NOTE: 展开收起组件重构，修复 Tabs 嵌套展开收起组件的问题；新增右下角按钮

###2018-06-19
   FE: wangkai37
   UE: zhuxiaolei
   NOTE: 样式修复

###2017-11-16
   FE: yaochang
   PM:
   NOTE: 新增展开收起新交互组件
   三级单:

###2018-5-16
   FE: diaojiajia
   PM:
   NOTE: NA2.0添加展开动画
   三级单:

###2018-6-28
FE: diaojiajia
PM:
NOTE: NA2.0添加展开动画
三级单: