###2019-06-13
   FE: pengchangzhou
   NOTE: 增加背景色根据数据不同而变化
###2019-04-15
   FE: wangkai37
   NOTE: 增加背景色渐变

###2019-03-25
   FE: wangkai37
   NOTE: 增加 pc 的兼容

###2019-3-11
   FE: donghualei
   NOTE: 修改keheader组件上属性

###2019-3-6
   FE: donghualei
   NOTE: 支持kgheader给title区域增加data-module属性

###2019-02-19
   FE: donghualei
   NOTE: 在c-tabs-item的节点上增加了data-module属性，可以让tabs组件内可以获取到该属性

###2019-02-15
   FE: wangkai37
   NOTE: 新增反馈、评价、分享功能

###2019-01-28
   FE: wangkai37
   NOTE: 新增反馈弹层

###2019-01-08
   FE: wangkai37
   NOTE: 新增控制头图垂直居中的参数

###2018-12-21
   FE: yaochang
   NOTE: 调整 PC 下的头图高度

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-11-08
   FE: wangkai37
   NOTE: KgHeader 增加自定义标题栅格功能；7n 标题字号策略优化

###2018-10-25
   FE: zhangjingyuan02
   NOTE: 添加限制点击态开启条件：如果没有传params或者params.tcUrl

###2018-09-21
   FE: wangkai37
   NOTE: 增加导航栏滑动的功能；透传头图比例参数

###2018-07-24
   FE: wangkai37
   NOTE: 修复头图区域图片未加载完成时显示默认图影响体验的问题

###2018-06-28
   FE: zhangwentao
   NOTE: 修改 NA2.0 点击态
