###2019-02-26
   FE: donghualei
   NOTE: 增加footer的data-module属性

###2019-02-19
   FE: wangkai37
   NOTE: 暴露左侧脚注点击事件

###2019-01-23
   FE: wangkai37
   NOTE: 暴露反馈事件

###2019-01-09
   FE: wangkai37
   NOTE: 反馈升级，增加评价参数

###2018-11-28
   FE: wangkai37
   NOTE: 增加 data-module

###2018-11-06
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-09-05
   FE: wangkai37
   NOTE: 添加反馈点击日志

###2018-07-01
   FE: wangkai37
   NOTE: 修复 MipIcon sf 链接跳转不正确的问题

###2018-06-30
   FE: wangkai37
   NOTE: 暴露反馈按钮点击事件

###2018-05-30
   FE: zhangwentao
   NOTE: footer 右侧链接嵌入点击态组件，默认关，开启方式添加属性 `right-touchable`，因为结构变化，修改了 icon 定位

###2018-05-24
   FE: wangkai37
   NOTE: 修改自然结果来源字体大小；优化代码结构；优化示例

###2018-05-17
   FE: wangkai37
   NOTE: 增加 MipIcon 组件

###2018-05-02
   FE: huxiaohui02,wangkai37
   NOTE: 增加新的反馈入口

###2018-02-09
   FE: wangkai37
   NOTE: 修复只有右侧图标时，右侧跳转区域过小的问题；
   三级单:

###2018-02-01
   FE: wangkai37
   NOTE: 修复当只有右侧文字时文字没有右对齐栅格问题；修复当只有图标时样式显示错误问题；
   三级单:

###2018-01-24
   FE: wangkai37
   NOTE: 修复右侧图标间距的问题；修复华为P10显示异常的问题；
   三级单:

###2018-01-09
   FE: wangkai37
   PM:
   NOTE: Footer修复图标右侧垂直居中的问题
   三级单:

###2018-01-08
   FE: wangkai37
   PM:
   NOTE: Footer组件右侧增加文字截断
   三级单:
