###2019-05-07
   FE: wangkai37
   NOTE: 增加标题粗细参数 fontWeight

###2019-04-11
   FE: wangkai37
   NOTE: 增加标题截断策略

###2019-02-26
   FE: donghualei
   NOTE: 增加footer的data-module属性

###2019-02-19
   FE: wangkai37
   NOTE: 暴露左侧脚注点击事件

###2018-12-21
   FE: yaochang
   NOTE: 适配 PC，PC 智库增加边框并且应用有框栅格

###2018-11-21
   FE: zhangwentao
   NOTE: 点击态设置 rl-highlight-self

###2018-11-20
   FE: wangkai37
   NOTE: 增加 title-data-module

###2018-11-14
   FE: fanyurong
   NOTE: 小程序调起统一加data-xcx标识

###2018-11-02
   FE: zhangwentao
   NOTE: 修改整卡可点链接属性数据来源为 urlParams

###2018-10-25
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，去掉原组件内 js 实现

###2018-10-23
   FE: wangkai37
   NOTE: 增加 data-module 参数

###2018-10-16
   FE: liyuhang01
   NOTE: 无障碍容错

###2018-09-28
   FE: wangkai37
   NOTE: 增加 color props

###2018-09-11
   FE: wangkai37
   NOTE: 增加边框

###2018-09-10
   FE: liyuhang01
   NOTE: 增加组件无障碍支持

###2018-07-31
   FE: wangkai37
   NOTE: 修改一级标题截断方式

###2018-07-06
   FE: zhangwentao
   NOTE: 修改文档，点击态优化，修改整卡可点背景 z-index

###2018-07-02
   FE: wangkai37
   NOTE: 增加反馈按钮点击事件

###2018-05-24
   FE: zhangwentao
   NOTE: 支持整卡可点，默认关，开启方式添加属性 `touchable`

###2018-05-21
   FE: wangkai37
   NOTE: 增加在标题上方的自定义内容 slot

###2018-05-02
   FE: wangkai37
   NOTE: 增加新的反馈入口

###2018-04-02
   FE: 王凯
   NOTE: 修复文档中 Sigma 卡 / Normal 卡 强弱样式退化示例；补充 tplInfo 属性说明；
   三级单:

###2018-03-09
   FE: 王凯
   NOTE: 增加 tplInfo 属性，如果 tplInfo === 'sigma'，则自动添加 c-sigma-container 类
   三级单:

###2017-12-1
   FE: yaochang
   NOTE: 标题添加点击态
   三级单:

###2017-12-20
   FE: xinyangxi
   NOTE: 增加反馈入口
   三级单:
