###2019-3-11
   FE: donghualei
   NOTE: 修复tabs组件的传参导致同时会落到tabs-item组件上的bug

###2019-2-19
   FE: donghualei
   NOTE: 增加data-module属性，支持在list中增加dataModule属性，组件给绑定到dom节点上

###2018-12-21
   FE: yaochang
   NOTE: 调整 PC 下的左右 margin 为9px

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-09-10
   FE: liyuhang01
   NOTE: 增加组件无障碍支持

### 2018-08-15
   FE: wangkai37
   NOTE: 配合展开收起组件，增加强制开启 TabsContent 高度变化 transition 的属性，和动效结束的方法；删除旧示例

### 2018-07-31
   FE: chenxiao07
   NOTE: 修复异步情况下的报错

### 2018-06-28
   FE: zhangwentao
   NOTE: tab 和 content 增加屏蔽触发整卡点击态功能

### 2018-05-21
    FE: zhangjingyuan02
    PM:
    NOTE:
        1. 去掉tabs切换下划线拉伸动画
        2. 添加内容渐显效果
    三级单:

### 2017-12-12
    FE: yaochang
    PM:
    NOTE:
        1. 修复切换 tab 内容抖动的问题
        2. 修改代码和文档规范问题
        3. 将 tab 内容独立成子模块
    三级单:

###2017-12-1
   FE: songshaokang
   PM:
   NOTE: 添加 tab bar 切换动画，添加内容切换动画，添加点击态
   三级单:

###2017-11-02
   FE: yaochang
   PM:
   NOTE: fix issue atom-component-24
   三级单:
