###2018-10-28
   FE:liyuhang01
   NOTE:组件无障碍升级

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

###2018-10-28
   FE:liyuhang01
   NOTE:组件无障碍升级

###2018-09-27
   FE: wangkai37
   NOTE: 增加控制 overflow css 属性的 props

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

### 2018-06-28
   FE: zhangwentao
   NOTE: 增加屏蔽整卡点击态功能

###2018-05-21
   FE: wangkai37
   NOTE: 传入 bindToWrapper 属性，设置绑定事件至该元素上而非全局；使用新的 better-scroll apm 版本