###2019-6-28
   FE:wangkai37
   NOTE:修复小程序来源样式问题

###2019-6-17
   FE:wangkai37
   NOTE:增加小程序来源

###2019-5-20
   FE:wangkai37
   NOTE:修复不传url时a标签显示href(unknown)的问题

###2019-4-24
   FE:wangkai37
   NOTE:增加弹层按钮阻止冒泡和单独的点击事件

###2019-3-28
   FE:wangkai37
   NOTE:修复timeData设置为空字符串触发错误判断的问题

###2019-2-18
   FE:wangkai37
   NOTE:优化判断是否是数字的逻辑

###2019-1-23
   FE:wangkai37
   NOTE:暴露反馈事件

###2019-1-10
   FE:wangkai37
   NOTE:新增反馈、评价配置

###2018-10-28
   FE:liyuhang01
   NOTE:组件无障碍升级

###2018-07-03
   FE: zhangwentao
   NOTE: 修改点击态透明度和类型, 优化文档 增加 NA2.0 整卡可点示例

###2018-06-29
   FE:wangkai37
   NOTE:增加传入熊掌号数据

###2018-06-05
   FE:wangkai37
   NOTE:修改图片rem单位为px

###2018-05-17
   FE:wangkai37
   NOTE:增加来源图片跳转功能及点击态；增加自定义插槽；

###2018-02-06
   FE:wangkai37
   NOTE:修复栅格样式不正确的问题；增加time为空判断；