###2019-04-15
   FE: wangkai37
   NOTE: 增加图片圆角配置参数

###2019-03-25
   FE: wangkai37
   NOTE: 增加 pc 的兼容

###2019-02-19
   FE: liyuhang01
   NOTE: 修复情景页返回后视频消失问题

###2018-12-27
   FE: wangkai37
   NOTE: 修复没有透传 item.params 的问题

###2018-12-06
   FE:liyuhang01
   NOTE:增加圆角

###2018-12-01
   FE: liyuhang01
   NOTE: 增加 video-content 组件 8N 2:1 图片展开

###2018-11-27
   FE: liyuhang01
   NOTE: 增加 data-module

###2018-11-06
   FE: liyuhang01
   NOTE: 增加 video 组件无障碍支持

###2018-10-16
   FE: liyuhang01
   NOTE: 修复 videoContent 动图模式时视频报警问题

###2018-10-10
   FE: liyuhang01
   NOTE: 防止 videoContent 点击穿透

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-09-17
   FE: liyuhang01
   NOTE: 修复进 SF 页视频未停止 Bug && 增加组件无障碍

###2018-09-10
   FE: liyuhang01
   NOTE: 增加 videoCol 组件无障碍支持

###2018-09-04
   FE: liyuhang01
   NOTE: 完成 videoContent 组件

###2018-06-04
   FE: wangkai37
   NOTE: 增加 schema

###2018-05-03
   FE: chenxiao07
   NOTE: 修改 '0' 导致的前后端不一致问题

###2018-04-18
   FE: wangkai37
   NOTE: 暴露 Image 组件的 default-image-type 默认图属性
