###2019-04-17
   FE: wangkai37
   NOTE: 增加边线，小重构

###2019-03-28
   FE: wangkai37
   NOTE: 修复切换到情景页以后 vm.playerObj 不存在依然调用方法报错的问题

###2019-03-14
   FE: meixuguang
   NOTE: 升级 @baidu/audio-player 至 1.0.9 版本，解决 iOS 设备继续播放会从头播放的问题

###2018-12-25
   FE: liyuhang01
   NOTE: 升级圆角

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，修改整卡点击态屏蔽方式

###2018-10-22
   FE: liyuhang01
   NOTE: 组件支持无障碍

###2018-09-03
   FE: wangkai37
   NOTE: 修复 svg 压缩导致图标样式异常问题

###2018-08-10
   FE: yangqifan
   NOTE: 默认开启进度

###2018-07-11
   FE: zhangwentao
   NOTE: 屏蔽整卡点击态
