###2018-11-14
   FE: fanyurong
   NOTE: 小程序调起统一加data-xcx标识

###2018-11-02
   FE: zhangwentao
   NOTE: 优化文档

###2018-10-11
   FE: zhangwentao
   NOTE: 升级点击态实现方案为 responsive-link，去掉原组件内 js 实现，去掉 expand 支持

###2018-09-17
   FE: wangkai37
   NOTE: 增加 css scoped

###2018-08-16
   FE: zhangwentao
   NOTE: 提供关闭点击态的接口，解决简单端上返回时点击态留存问题，服务端渲染优化

###2018-05-24
   FE: zhangwentao
   NOTE: 新增功能，点击态组件支持整体点出功能，且支持扩展点击触发区域，相关属性 `url` `urlParams` `expand`；新增 `borderRadius` 属性
